defmodule Skuld.Effects.Port.Contract do
  @moduledoc """
  Macro for defining typed port contracts with `defport` declarations.

  Builds on `HexPort` to generate the plain behaviour and port facade,
  then adds Skuld-specific effectful layers on top.

  A Port contract defines a set of operations, generating:

    * **Behaviour** (`__MODULE__.Behaviour`) — plain Elixir callbacks for
      non-effectful implementations (generated by HexPort)
    * **Port** (`__MODULE__.Port`) — plain dispatch facade via config or
      test handlers (generated by HexPort)
    * **Effectful behaviour** (`__MODULE__.Effectful`) — computation-returning
      callbacks for effectful implementations (generated by Skuld)
    * **Caller functions** — typed public API returning `computation(return_type)`,
      which also satisfy the Effectful behaviour (generated by Skuld)
    * **Bang variants** — unwrap `{:ok, v}` or dispatch Throw (when applicable)
    * **Key helpers** — for test stub matching
    * **Introspection** — `__port_operations__/0` (generated by HexPort)

  ## Behaviour vs Effectful

  The contract generates two behaviour modules:

    * `MyContract.Behaviour` — callbacks return plain values. Use for
      non-effectful implementations that are called via `Port.with_handler/2`
      (`:direct` resolver) or via `MyContract.Port` (config dispatch).
    * `MyContract.Effectful` — callbacks return `computation(return_type)`. Use
      for effectful implementations that are called via the `:effectful` resolver
      in `Port.with_handler/2` or wrapped with `Port.Adapter.Effectful`.

  The contract module's own caller functions satisfy the Effectful behaviour
  (they return computations that emit Port effects).

  ## Bang Variant Generation

  Bang variants (`name!`) are generated based on the return type:

    * **Auto-detect** (default): If the return type contains `{:ok, T}`, a bang
      variant is generated that unwraps `{:ok, value}` or dispatches `Throw` on
      `{:error, reason}`. If no `{:ok, T}` is found, no bang is generated.
    * **`bang: true`**: Force bang generation with standard `{:ok, v}` / `{:error, r}`
      unwrapping, even if the return type doesn't match the pattern.
    * **`bang: false`**: Suppress bang generation even if the return type matches.
    * **`bang: unwrap_fn`**: Generate a bang that first applies `unwrap_fn` to the
      raw result (which must return `{:ok, v}` or `{:error, r}`), then unwraps.

  ## Example

      defmodule MyApp.Repository do
        use Skuld.Effects.Port.Contract

        # Auto-detected: has {:ok, T}, bang generated automatically
        defport get_todo(tenant_id :: String.t(), id :: String.t()) ::
                  {:ok, Todo.t()} | {:error, term()}

        # No {:ok, T} in return type, no bang generated
        defport find_user(id :: String.t()) :: User.t() | nil

        # Force bang with custom unwrap (nil -> error, value -> ok)
        defport find_user(id :: String.t()) :: User.t() | nil,
          bang: fn
            nil -> {:error, :not_found}
            user -> {:ok, user}
          end

        # Suppress bang even though return type has {:ok, T}
        defport raw_query(sql :: String.t()) ::
                  {:ok, term()} | {:error, term()},
                  bang: false
      end

  This generates:

      # Plain behaviour (generated by HexPort)
      MyApp.Repository.Behaviour
      @callback get_todo(String.t(), String.t()) :: {:ok, Todo.t()} | {:error, term()}

      # Plain dispatch facade (generated by HexPort)
      MyApp.Repository.Port
      def get_todo(tenant_id, id) — dispatches via HexPort.Dispatch

      # Effectful behaviour (generated by Skuld)
      MyApp.Repository.Effectful
      @callback get_todo(String.t(), String.t()) :: computation({:ok, Todo.t()} | {:error, term()})

      # Caller (returns computation, satisfies Effectful behaviour)
      @spec get_todo(String.t(), String.t()) :: Types.computation({:ok, Todo.t()} | {:error, term()})
      def get_todo(tenant_id, id)

      # Bang (unwraps or throws) — auto-detected from {:ok, T}
      @spec get_todo!(String.t(), String.t()) :: Types.computation(Todo.t())
      def get_todo!(tenant_id, id)

      # Key helper (for test stubs)
      def key(:get_todo, tenant_id, id)

  ## Plain Implementation

      defmodule MyApp.Repository.Ecto do
        @behaviour MyApp.Repository.Behaviour

        @impl true
        def get_todo(tenant_id, id), do: ...
      end

  ## Handler Installation

      my_comp
      |> Port.with_handler(%{MyApp.Repository => MyApp.Repository.Ecto})
      |> Comp.run!()

  ## Effectful Implementation

  For the reverse direction — plain Elixir code calling into effectful
  implementations — see `Skuld.Effects.Port.Adapter.Effectful`.

      # Effectful implementation satisfies Effectful behaviour
      defmodule MyApp.Repository.EffectfulImpl do
        @behaviour MyApp.Repository.Effectful
        defcomp get_todo(tenant_id, id) do
          # ... effectful code returning computation(return_type)
        end
      end

      # Effectful adapter satisfies Behaviour
      defmodule MyApp.Repository.EffectfulImpl.Adapter do
        use Skuld.Effects.Port.Adapter.Effectful,
          contract: MyApp.Repository,
          impl: MyApp.Repository.EffectfulImpl,
          stack: &MyApp.Stacks.repository/1
      end
  """

  @doc false
  defmacro __using__(_opts) do
    quote do
      # HexPort generates X.Behaviour, X.Port, and __port_operations__/0
      use HexPort
      # Skuld adds effectful layers after HexPort's __before_compile__ runs
      @before_compile Skuld.Effects.Port.Contract
    end
  end

  # defport macro is provided by HexPort via `use HexPort`

  @doc false
  defmacro __before_compile__(env) do
    # __port_operations__/0 is already defined by HexPort's __before_compile__
    # which ran before this one (registered first via `use HexPort`).
    operations = Module.get_attribute(env.module, :port_operations) |> Enum.reverse()

    provider_module = Module.concat(env.module, Effectful)

    provider_callbacks = Enum.map(operations, &generate_provider_callback/1)
    callers = Enum.map(operations, &generate_caller/1)

    bangs =
      operations
      |> Enum.filter(fn op -> op.bang_mode != :none end)
      |> Enum.map(&generate_bang/1)

    key_helpers = Enum.map(operations, &generate_key_helper/1)

    quote do
      defmodule unquote(provider_module) do
        @moduledoc """
        Effectful behaviour for `#{inspect(unquote(env.module))}`.

        Defines computation-returning callbacks — implementations return
        `computation(return_type)` values. Implementations satisfying this
        behaviour can be used with `Port.with_handler/2` and are
        auto-detected as effectful resolvers.

        Use `use #{inspect(unquote(provider_module))}` (preferred) or
        `@behaviour #{inspect(unquote(provider_module))}` plus a manual
        `def __port_effectful__?, do: true` marker.

        The contract module's own caller functions satisfy this behaviour.
        """

        defmacro __using__(_opts) do
          behaviour_mod = unquote(provider_module)

          quote do
            @behaviour unquote(behaviour_mod)
            def __port_effectful__?, do: true
          end
        end

        unquote_splicing(provider_callbacks)
      end

      unquote_splicing(callers)
      unquote_splicing(bangs)
      unquote_splicing(key_helpers)
    end
  end

  # -------------------------------------------------------------------
  # Code Generation: Effectful callbacks
  # -------------------------------------------------------------------

  defp generate_provider_callback(%{
         name: name,
         param_names: param_names,
         param_types: param_types,
         return_type: return_type
       }) do
    callback_params =
      Enum.zip(param_names, param_types)
      |> Enum.map(fn {pname, ptype} ->
        {:"::", [], [{pname, [], nil}, ptype]}
      end)

    comp_type = {:computation, [], [return_type]}

    quote do
      @callback unquote(name)(unquote_splicing(callback_params)) ::
                  Skuld.Comp.Types.unquote(comp_type)
    end
  end

  # -------------------------------------------------------------------
  # Code Generation: Effectful caller functions
  # -------------------------------------------------------------------

  defp generate_caller(%{
         name: name,
         param_names: param_names,
         param_types: param_types,
         return_type: return_type,
         user_doc: user_doc
       }) do
    param_vars = Enum.map(param_names, fn pname -> {pname, [], nil} end)
    args_list = param_vars
    spec_params = param_types
    comp_type = {:computation, [], [return_type]}

    doc_ast =
      if user_doc do
        {_line, doc_content} = user_doc

        quote do
          @doc unquote(doc_content)
        end
      else
        doc_string =
          "Port operation: `#{name}/#{length(param_names)}`\n\nDispatches to the configured implementation via the Port effect.\n"

        quote do
          @doc unquote(doc_string)
        end
      end

    quote do
      unquote(doc_ast)
      @spec unquote(name)(unquote_splicing(spec_params)) :: Skuld.Comp.Types.unquote(comp_type)
      def unquote(name)(unquote_splicing(param_vars)) do
        Skuld.Effects.Port.request(__MODULE__, unquote(name), unquote(args_list))
      end
    end
  end

  # -------------------------------------------------------------------
  # Code Generation: Effectful bang variants
  # -------------------------------------------------------------------

  defp generate_bang(%{
         name: name,
         param_names: param_names,
         param_types: param_types,
         return_type: return_type,
         bang_mode: bang_mode
       }) do
    bang_name = :"#{name}!"
    param_vars = Enum.map(param_names, fn pname -> {pname, [], nil} end)
    args_list = param_vars

    spec_params = param_types

    unwrapped = HexPort.Contract.extract_success_type(return_type)
    comp_type = {:computation, [], [unwrapped]}

    {doc_string, body_ast} =
      case bang_mode do
        :standard ->
          doc =
            "Port operation: `#{bang_name}/#{length(param_names)}`\n\nLike `#{name}/#{length(param_names)}` but unwraps `{:ok, value}` or dispatches `Throw` on error.\n"

          body =
            quote do
              Skuld.Effects.Port.request!(__MODULE__, unquote(name), unquote(args_list))
            end

          {doc, body}

        {:custom, unwrap_fn_ast} ->
          doc =
            "Port operation: `#{bang_name}/#{length(param_names)}`\n\nLike `#{name}/#{length(param_names)}` but applies a custom unwrap function, then unwraps `{:ok, value}` or dispatches `Throw` on error.\n"

          body =
            quote do
              Skuld.Effects.Port.request_bang(
                __MODULE__,
                unquote(name),
                unquote(args_list),
                unquote(unwrap_fn_ast)
              )
            end

          {doc, body}
      end

    quote do
      @doc unquote(doc_string)
      @spec unquote(bang_name)(unquote_splicing(spec_params)) ::
              Skuld.Comp.Types.unquote(comp_type)
      def unquote(bang_name)(unquote_splicing(param_vars)) do
        unquote(body_ast)
      end
    end
  end

  # -------------------------------------------------------------------
  # Code Generation: Key helpers (for Skuld Port effect test stubs)
  # -------------------------------------------------------------------

  defp generate_key_helper(%{name: name, param_names: param_names}) do
    param_vars = Enum.map(param_names, fn pname -> {pname, [], nil} end)
    args_list = param_vars

    doc_string =
      if param_names != [] do
        param_example = param_names |> Enum.map_join(", ", &to_string/1)

        "Build a test stub key for the `#{name}` port operation.\n\nUse with `Port.with_test_handler/2`:\n\n    Port.with_test_handler(%{\n      __MODULE__.key(:#{name}, #{param_example}) => {:ok, result}\n    })\n"
      else
        "Build a test stub key for the `#{name}` port operation.\n\nUse with `Port.with_test_handler/2`:\n\n    Port.with_test_handler(%{\n      __MODULE__.key(:#{name}) => {:ok, result}\n    })\n"
      end

    quote do
      @doc unquote(doc_string)
      def key(unquote(name), unquote_splicing(param_vars)) do
        Skuld.Effects.Port.key(__MODULE__, unquote(name), unquote(args_list))
      end
    end
  end
end
