defmodule Skuld.Effects.Reader do
  @moduledoc """
  Reader effect - access an immutable environment value.

  Supports both simple single-context usage and multiple independent contexts via tags.

  ## Simple Usage (default tag)

      use Skuld.Syntax
      alias Skuld.Effects.Reader

      comp do
        cfg <- Reader.ask()
        cfg.name
      end
      |> Reader.with_handler(%{name: "alice"})
      |> Comp.run!()
      #=> "alice"

  ## Multiple Contexts (explicit tags)

      comp do
        db <- Reader.ask(:db)
        api <- Reader.ask(:api)
        {db.host, api.url}
      end
      |> Reader.with_handler(%{host: "localhost"}, tag: :db)
      |> Reader.with_handler(%{url: "https://api.example.com"}, tag: :api)
      |> Comp.run!()
      #=> {"localhost", "https://api.example.com"}

  ## Per-tag dispatch

  Each tag gets its own handler sig (a module atom) and compact operation
  atom. The tag is encoded in the sig, not in the operation args:

  - `ask` → `Comp.effect(sig(tag), Reader.Ask)` — bare atom, zero allocation
  """

  @behaviour Skuld.Comp.IHandle
  @behaviour Skuld.Comp.IInstall

  use Skuld.Comp.DefTaggedOp

  alias Skuld.Comp
  alias Skuld.Comp.Env
  alias Skuld.Comp.Types

  @compile {:inline, state_key: 1, sig: 1}

  @default_tag __MODULE__

  #############################################################################
  ## Operations (generated by def_tagged_op)
  ##
  ## def_tagged_op ask()  => def ask(tag \\ __MODULE__)
  ##                            Comp.effect(sig(tag), Reader.Ask)
  #############################################################################

  def_tagged_op ask()

  # Op atom as module attribute for use in handler
  @ask_op @__ask_op__

  #############################################################################
  ## Derived Operations
  #############################################################################

  @doc """
  Read and apply a function to the environment value.

  ## Examples

      Reader.asks(&Map.get(&1, :name))           # use default tag
      Reader.asks(:user, &Map.get(&1, :name))    # use explicit tag
  """
  @spec asks((term() -> term())) :: Types.computation()
  def asks(f) when is_function(f, 1) do
    Comp.map(ask(), f)
  end

  @spec asks(atom(), (term() -> term())) :: Types.computation()
  def asks(tag, f) when is_atom(tag) and is_function(f, 1) do
    Comp.map(ask(tag), f)
  end

  @doc """
  Run a computation with a modified environment value.

  ## Examples

      Reader.local(&Map.put(&1, :debug, true), comp)           # use default tag
      Reader.local(:config, &Map.put(&1, :debug, true), comp)  # use explicit tag
  """
  @spec local((term() -> term()), Types.computation()) :: Types.computation()
  def local(modify, comp) when is_function(modify, 1) do
    local(@default_tag, modify, comp)
  end

  @spec local(atom(), (term() -> term()), Types.computation()) :: Types.computation()
  def local(tag, modify, comp) when is_atom(tag) and is_function(modify, 1) do
    state_key = state_key(tag)

    Comp.scoped(comp, fn env ->
      current = Env.get_state!(env, state_key)
      modified_env = Env.put_state(env, state_key, modify.(current))
      finally_k = fn value, e -> {value, Env.put_state(e, state_key, current)} end
      {modified_env, finally_k}
    end)
  end

  #############################################################################
  ## Handler Installation
  #############################################################################

  @doc """
  Install a scoped Reader handler for a computation.

  ## Options

  - `tag` - the context tag (default: `Skuld.Effects.Reader`)

  ## Examples

      # Simple usage with default tag
      comp do
        cfg <- Reader.ask()
        cfg.name
      end
      |> Reader.with_handler(%{name: "alice"})
      |> Comp.run!()
      #=> "alice"

      # With explicit tag
      comp do
        db <- Reader.ask(:db)
        db.host
      end
      |> Reader.with_handler(%{host: "localhost"}, tag: :db)
      |> Comp.run!()
      #=> "localhost"

      # Multiple contexts
      comp do
        db <- Reader.ask(:db)
        cache <- Reader.ask(:cache)
        {db, cache}
      end
      |> Reader.with_handler(%{host: "db.local"}, tag: :db)
      |> Reader.with_handler(%{host: "cache.local"}, tag: :cache)
      |> Comp.run!()
      #=> {%{host: "db.local"}, %{host: "cache.local"}}
  """
  @spec with_handler(Types.computation(), term(), keyword()) :: Types.computation()
  def with_handler(comp, value, opts \\ []) do
    tag = Keyword.get(opts, :tag, @default_tag)
    output = Keyword.get(opts, :output)
    suspend = Keyword.get(opts, :suspend)
    handler_sig = sig(tag)
    sk = state_key(tag)

    scoped_opts =
      []
      |> then(fn o -> if output, do: Keyword.put(o, :output, output), else: o end)
      |> then(fn o -> if suspend, do: Keyword.put(o, :suspend, suspend), else: o end)

    # Op atom is fixed (not per-tag) — the tag is in the sig
    ask_op = @ask_op

    handler = fn args, env, k ->
      case args do
        ^ask_op ->
          value = Env.get_state!(env, sk)
          k.(value, env)
      end
    end

    comp
    |> Comp.with_scoped_state(sk, value, scoped_opts)
    |> Comp.with_handler(handler_sig, handler)
  end

  @doc """
  Install Reader handler via catch clause syntax.

  Accepts either `value` or `{value, opts}`:

      catch
        Reader -> %{config: true}
        Reader -> {%{config: true}, tag: :my_reader}
  """
  @impl Skuld.Comp.IInstall
  def __handle__(comp, {value, opts}) when is_list(opts), do: with_handler(comp, value, opts)
  def __handle__(comp, value), do: with_handler(comp, value)

  @doc "Extract the context value for the given tag from an env"
  @spec get_context(Types.env(), atom()) :: term()
  def get_context(env, tag \\ @default_tag) do
    Env.get_state(env, state_key(tag))
  end

  #############################################################################
  ## IHandle Implementation
  #############################################################################

  @impl Skuld.Comp.IHandle
  def handle(op, env, k) do
    case op do
      @ask_op ->
        # Default-tag handler (used by with_handler when no tag given
        # and handler_sig == __MODULE__)
        value = Env.get_state!(env, state_key(@default_tag))
        k.(value, env)
    end
  end

  #############################################################################
  ## State Key Helper
  #############################################################################

  @doc """
  Returns the env.state key used for a given tag.

  Useful for configuring EffectLogger's `state_keys` filter.

  ## Examples

      # Only capture Reader context in EffectLogger snapshots
      EffectLogger.with_logging(state_keys: [Reader.state_key(:config)])

      # Multiple contexts
      EffectLogger.with_logging(state_keys: [
        Reader.state_key(:db),
        Reader.state_key(:api)
      ])
  """
  @spec state_key(atom()) :: {module(), atom()}
  def state_key(tag), do: {__MODULE__, tag}
end
