defmodule Skuld.Effects.State do
  @moduledoc """
  State effect - mutable state threaded through computation.

  Supports both simple single-state usage and multiple independent states via tags.

  ## Simple Usage (default tag)

      use Skuld.Syntax
      alias Skuld.Effects.State

      comp do
        n <- State.get()
        _ <- State.put(n + 1)
        n
      end
      |> State.with_handler(0)
      |> Comp.run!()
      #=> 0

  ## Multiple States (explicit tags)

      comp do
        _ <- State.put(:counter, 0)
        _ <- State.modify(:counter, &(&1 + 1))
        count <- State.get(:counter)
        _ <- State.put(:name, "alice")
        name <- State.get(:name)
        {count, name}
      end
      |> State.with_handler(0, tag: :counter)
      |> State.with_handler("", tag: :name)
      |> Comp.run!()
      #=> {1, "alice"}

  ## Per-tag dispatch

  Each tag gets its own handler sig (a module atom) and compact operation
  atoms. The tag is encoded in the sig, not in the operation args, so
  operations carry only the data they need:

  - `get` → `Comp.effect(sig, State.Get)` — bare atom, zero allocation
  - `put` → `Comp.effect(sig, {State.Put, value})` — minimal 2-tuple
  """

  @behaviour Skuld.Comp.IHandle
  @behaviour Skuld.Comp.IInstall

  use Skuld.Comp.DefTaggedOp

  alias Skuld.Comp
  alias Skuld.Comp.Env
  alias Skuld.Comp.Types
  alias Skuld.Data.Change

  @compile {:inline, state_key: 1, sig: 1}

  @default_tag __MODULE__

  #############################################################################
  ## Operations (generated by def_tagged_op)
  ##
  ## def_tagged_op get()         => def get(tag \\ __MODULE__)
  ##                                  Comp.effect(sig(tag), State.Get)
  ##
  ## def_tagged_op put(value)    => def put(tag \\ __MODULE__, value)
  ##                                  Comp.effect(sig(tag), {State.Put, value})
  ##
  ## Also generates sig/1:
  ##   sig(State)     => State           (identity — no concat needed)
  ##   sig(:counter)  => Skuld.Effects.State.Counter
  #############################################################################

  def_tagged_op get()
  def_tagged_op put(value)

  # Op atoms as module attributes for use in handlers
  @get_op @__get_op__
  @put_op @__put_op__

  #############################################################################
  ## Derived Operations
  #############################################################################

  @doc """
  Modify the state with a function, returning the old value.

  ## Examples

      State.modify(&(&1 + 1))              # use default tag
      State.modify(:counter, &(&1 + 1))    # use explicit tag
  """
  @spec modify((term() -> term())) :: Types.computation()
  def modify(f) when is_function(f, 1) do
    modify(@default_tag, f)
  end

  @spec modify(atom(), (term() -> term())) :: Types.computation()
  def modify(tag, f) when is_atom(tag) and is_function(f, 1) do
    Comp.bind(get(tag), fn old ->
      Comp.bind(put(tag, f.(old)), fn _ ->
        Comp.pure(old)
      end)
    end)
  end

  @doc """
  Get a value derived from the state.

  ## Examples

      State.gets(&Map.get(&1, :name))              # use default tag
      State.gets(:user, &Map.get(&1, :name))       # use explicit tag
  """
  @spec gets((term() -> term())) :: Types.computation()
  def gets(f) when is_function(f, 1) do
    gets(@default_tag, f)
  end

  @spec gets(atom(), (term() -> term())) :: Types.computation()
  def gets(tag, f) when is_atom(tag) and is_function(f, 1) do
    Comp.map(get(tag), f)
  end

  #############################################################################
  ## Handler Installation
  #############################################################################

  @doc """
  Install a scoped State handler for a computation.

  ## Options

  - `tag` - the state tag (default: `Skuld.Effects.State`)
  - `output` - optional function `(result, final_state) -> new_result`
    to transform the result before returning.

  ## Examples

      # Simple usage with default tag
      comp do
        x <- State.get()
        _ <- State.put(x + 1)
        x
      end
      |> State.with_handler(0)
      |> Comp.run!()
      #=> 0

      # With explicit tag
      comp do
        x <- State.get(:counter)
        _ <- State.put(:counter, x + 1)
        x
      end
      |> State.with_handler(0, tag: :counter)
      |> Comp.run!()
      #=> 0

      # Include final state in result
      comp do
        _ <- State.modify(&(&1 + 1))
        :done
      end
      |> State.with_handler(5, output: fn result, state -> {result, state} end)
      |> Comp.run!()
      #=> {:done, 6}

      # Multiple states
      comp do
        a <- State.get(:a)
        b <- State.get(:b)
        {a, b}
      end
      |> State.with_handler(1, tag: :a)
      |> State.with_handler(2, tag: :b)
      |> Comp.run!()
      #=> {1, 2}
  """
  @spec with_handler(Types.computation(), term(), keyword()) :: Types.computation()
  def with_handler(comp, initial, opts \\ []) do
    tag = Keyword.get(opts, :tag, @default_tag)
    output = Keyword.get(opts, :output)
    suspend = Keyword.get(opts, :suspend)
    handler_sig = sig(tag)
    sk = state_key(tag)

    scoped_opts =
      []
      |> then(fn o -> if output, do: Keyword.put(o, :output, output), else: o end)
      |> then(fn o -> if suspend, do: Keyword.put(o, :suspend, suspend), else: o end)

    # Op atoms are fixed (not per-tag) — the tag is in the sig
    get_op = @get_op
    put_op = @put_op

    handler = fn args, env, k ->
      case args do
        ^get_op ->
          value = Env.get_state!(env, sk)
          k.(value, env)

        {^put_op, value} ->
          old_value = Env.get_state!(env, sk)
          new_env = Env.put_state(env, sk, value)
          k.(Change.new(old_value, value), new_env)
      end
    end

    comp
    |> Comp.with_scoped_state(sk, initial, scoped_opts)
    |> Comp.with_handler(handler_sig, handler)
  end

  @doc """
  Install State handler via catch clause syntax.

  Accepts either `initial` or `{initial, opts}`:

      catch
        State -> 0                          # initial value
        State -> {0, output: fn r, s -> {r, s} end}  # with opts
  """
  @impl Skuld.Comp.IInstall
  def __handle__(comp, {initial, opts}) when is_list(opts), do: with_handler(comp, initial, opts)
  def __handle__(comp, initial), do: with_handler(comp, initial)

  @doc "Extract the state for the given tag from an env"
  @spec get_state(Types.env(), atom()) :: term()
  def get_state(env, tag \\ @default_tag) do
    Env.get_state(env, state_key(tag))
  end

  #############################################################################
  ## IHandle Implementation (kept for IHandle contract — handler closures
  ## are used directly in with_handler, but this satisfies the behaviour)
  #############################################################################

  @impl Skuld.Comp.IHandle
  def handle(@get_op, env, k) do
    value = Env.get_state!(env, state_key(@default_tag))
    k.(value, env)
  end

  @impl Skuld.Comp.IHandle
  def handle({@put_op, value}, env, k) do
    key = state_key(@default_tag)
    old_value = Env.get_state!(env, key)
    new_env = Env.put_state(env, key, value)
    k.(Change.new(old_value, value), new_env)
  end

  #############################################################################
  ## Op Atom Accessors (for EffectLogger tests etc.)
  #############################################################################

  @doc "Returns the get operation atom."
  @spec get_op() :: atom()
  def get_op, do: @get_op

  @doc "Returns the put operation atom."
  @spec put_op() :: atom()
  def put_op, do: @put_op

  #############################################################################
  ## State Key Helper
  #############################################################################

  @doc """
  Returns the env.state key used for a given tag.

  Useful for configuring EffectLogger's `state_keys` filter.

  ## Examples

      # Only capture State effect data in EffectLogger snapshots
      EffectLogger.with_logging(state_keys: [State.state_key(MyApp.Counter)])

      # Multiple states
      EffectLogger.with_logging(state_keys: [
        State.state_key(:counter),
        State.state_key(:user)
      ])
  """
  @spec state_key(atom()) :: atom()
  def state_key(tag), do: sig(tag)
end
