defmodule Skuld.Effects.Writer do
  @moduledoc """
  Writer effect - accumulate a log during computation.

  Supports both simple single-log usage and multiple independent logs via tags.

  ## Simple Usage (default tag)

      use Skuld.Syntax
      alias Skuld.Effects.Writer

      comp do
        _ <- Writer.tell("step 1")
        _ <- Writer.tell("step 2")
        :done
      end
      |> Writer.with_handler([], output: fn result, log -> {result, log} end)
      |> Comp.run!()
      #=> {:done, ["step 2", "step 1"]}

  ## Multiple Logs (explicit tags)

      comp do
        _ <- Writer.tell(:audit, "user logged in")
        _ <- Writer.tell(:metrics, {:counter, :login, 1})
        _ <- Writer.tell(:audit, "user viewed dashboard")
        :ok
      end
      |> Writer.with_handler([], tag: :audit, output: fn r, log -> {r, log} end)
      |> Writer.with_handler([], tag: :metrics)
      |> Comp.run!()
      #=> {:ok, ["user viewed dashboard", "user logged in"]}

  ## Per-tag dispatch

  Each tag gets its own handler sig (a module atom) and compact operation
  tuples. The tag is encoded in the sig, not in the operation args:

  - `tell(msg)` → `Comp.effect(sig(tag), {Writer.Tell, msg})` — minimal 2-tuple
  - `peek()`    → `Comp.effect(sig(tag), Writer.Peek)` — bare atom
  - `set_log`   → `Comp.effect(sig(tag), {Writer.SetLog, log})` — internal

  ## Scoped Operations and Throw

  The scoped operations (`listen`, `pass`, `censor`) use a peek-before/peek-after
  pattern to calculate captured logs. This means on abnormal exit (throw):

  - Logs written before the throw **persist** in state (not rolled back)
  - `listen` does not capture partial logs - the throw propagates out
  - `censor` does not apply its transform - logs leak out untransformed

  This "fire-and-forget" semantic is intentional for logging (you typically want
  to see logs leading up to an error).
  """

  @behaviour Skuld.Comp.IHandle
  @behaviour Skuld.Comp.IInstall

  use Skuld.Comp.DefTaggedOp

  alias Skuld.Comp
  alias Skuld.Comp.Env
  alias Skuld.Comp.Types

  @compile {:inline, state_key: 1, sig: 1}

  @default_tag __MODULE__

  #############################################################################
  ## Operations (generated by def_tagged_op)
  ##
  ## def_tagged_op tell(msg)  => def tell(tag \\ __MODULE__, msg)
  ##                                Comp.effect(sig(tag), {Writer.Tell, msg})
  ##
  ## def_tagged_op peek()     => def peek(tag \\ __MODULE__)
  ##                                Comp.effect(sig(tag), Writer.Peek)
  ##
  ## def_tagged_op set_log(log) => def set_log(tag \\ __MODULE__, log)
  ##                                  Comp.effect(sig(tag), {Writer.SetLog, log})
  #############################################################################

  def_tagged_op tell(msg)
  def_tagged_op peek()
  def_tagged_op set_log(log)

  # Op atoms as module attributes for use in handlers
  @tell_op @__tell_op__
  @peek_op @__peek_op__
  @set_log_op @__set_log_op__

  #############################################################################
  ## Effect Operations
  #############################################################################

  @doc """
  Run a computation and capture its log output.

  Returns `{result, captured_log}` where captured_log contains only
  the messages written during the inner computation.

  ## Examples

      Writer.listen(comp)          # use default tag
      Writer.listen(:audit, comp)  # use explicit tag
  """
  @spec listen(Types.computation()) :: Types.computation()
  def listen(comp) do
    listen(@default_tag, comp)
  end

  @spec listen(atom(), Types.computation()) :: Types.computation()
  def listen(tag, comp) when is_atom(tag) do
    Comp.bind(peek(tag), fn initial_log ->
      # Calculate initial length once (O(n))
      initial_length = length(initial_log)

      Comp.bind(comp, fn result ->
        Comp.bind(peek(tag), fn final_log ->
          # Calculate what was added (new logs are at the front)
          # Only one length call on final_log (O(n) once instead of twice)
          captured = Enum.take(final_log, length(final_log) - initial_length)
          Comp.pure({result, captured})
        end)
      end)
    end)
  end

  @doc """
  Run a computation that returns `{value, log_transform_fn}`.

  The transform function is applied to the logs written during the computation.

  ## Examples

      Writer.pass(comp)          # use default tag
      Writer.pass(:audit, comp)  # use explicit tag
  """
  @spec pass(Types.computation()) :: Types.computation()
  def pass(comp) do
    pass(@default_tag, comp)
  end

  @spec pass(atom(), Types.computation()) :: Types.computation()
  def pass(tag, comp) when is_atom(tag) do
    Comp.bind(peek(tag), fn initial_log ->
      # Calculate initial length once (O(n))
      initial_length = length(initial_log)

      Comp.bind(comp, fn {value, transform_fn} ->
        Comp.bind(peek(tag), fn final_log ->
          # Calculate captured logs
          # Only one length call on final_log (O(n) once instead of twice)
          captured = Enum.take(final_log, length(final_log) - initial_length)
          # Apply transform
          transformed = transform_fn.(captured)
          # Replace captured logs with transformed version
          new_log = transformed ++ initial_log

          Comp.bind(set_log(tag, new_log), fn _ ->
            Comp.pure(value)
          end)
        end)
      end)
    end)
  end

  @doc """
  Censor: transform all logs written during a computation.

  ## Examples

      Writer.censor(comp, &Enum.map(&1, fn m -> "[REDACTED]" end))
      Writer.censor(:audit, comp, &Enum.reverse/1)
  """
  @spec censor(Types.computation(), (list() -> list())) :: Types.computation()
  def censor(comp, transform_fn) when is_function(transform_fn, 1) do
    censor(@default_tag, comp, transform_fn)
  end

  @spec censor(atom(), Types.computation(), (list() -> list())) :: Types.computation()
  def censor(tag, comp, transform_fn) when is_atom(tag) and is_function(transform_fn, 1) do
    pass(
      tag,
      Comp.bind(comp, fn result ->
        Comp.pure({result, transform_fn})
      end)
    )
  end

  #############################################################################
  ## Handler Installation
  #############################################################################

  @doc """
  Install a scoped Writer handler for a computation.

  ## Options

  - `tag` - the log tag (default: `Skuld.Effects.Writer`)
  - `output` - optional function `(result, final_log) -> new_result`
    to transform the result before returning.

  ## Examples

      # Simple usage with default tag
      comp do
        _ <- Writer.tell("step 1")
        _ <- Writer.tell("step 2")
        :done
      end
      |> Writer.with_handler()
      |> Comp.run!()
      #=> :done

      # Include final log in result
      comp do
        _ <- Writer.tell("step 1")
        :done
      end
      |> Writer.with_handler([], output: fn result, log -> {result, log} end)
      |> Comp.run!()
      #=> {:done, ["step 1"]}

      # With explicit tag
      comp do
        _ <- Writer.tell(:audit, "action 1")
        :done
      end
      |> Writer.with_handler([], tag: :audit, output: fn r, log -> {r, log} end)
      |> Comp.run!()
      #=> {:done, ["action 1"]}

      # Multiple logs
      comp do
        _ <- Writer.tell(:foo, "message 1")
        _ <- Writer.tell(:bar, "message 2")
        :done
      end
      |> Writer.with_handler([], tag: :foo)
      |> Writer.with_handler([], tag: :bar)
      |> Comp.run!()
      #=> :done
  """
  @spec with_handler(Types.computation(), list(), keyword()) :: Types.computation()
  def with_handler(comp, initial \\ [], opts \\ []) do
    tag = Keyword.get(opts, :tag, @default_tag)
    output = Keyword.get(opts, :output)
    suspend = Keyword.get(opts, :suspend)
    handler_sig = sig(tag)
    sk = state_key(tag)

    scoped_opts =
      [default: []]
      |> then(fn o -> if output, do: Keyword.put(o, :output, output), else: o end)
      |> then(fn o -> if suspend, do: Keyword.put(o, :suspend, suspend), else: o end)

    # Op atoms are fixed (not per-tag) — the tag is in the sig
    tell_op = @tell_op
    peek_op = @peek_op
    set_log_op = @set_log_op

    handler = fn args, env, k ->
      case args do
        {^tell_op, msg} ->
          current = Env.get_state!(env, sk)
          updated = [msg | current]
          new_env = Env.put_state(env, sk, updated)
          k.(updated, new_env)

        ^peek_op ->
          current = Env.get_state!(env, sk)
          k.(current, env)

        {^set_log_op, new_log} ->
          new_env = Env.put_state(env, sk, new_log)
          k.(:ok, new_env)
      end
    end

    comp
    |> Comp.with_scoped_state(sk, initial, scoped_opts)
    |> Comp.with_handler(handler_sig, handler)
  end

  @doc """
  Install Writer handler via catch clause syntax.

  Accepts `nil`, `initial`, or `{initial, opts}`:

      catch
        Writer -> nil                          # empty initial
        Writer -> []                           # explicit empty initial
        Writer -> {[], output: fn r, l -> {r, Enum.reverse(l)} end}
  """
  @impl Skuld.Comp.IInstall
  def __handle__(comp, nil), do: with_handler(comp)
  def __handle__(comp, {initial, opts}) when is_list(opts), do: with_handler(comp, initial, opts)
  def __handle__(comp, initial), do: with_handler(comp, initial)

  @doc """
  Get the accumulated log from the environment.

  ## Examples

      Writer.get_log(env)          # use default tag
      Writer.get_log(env, :audit)  # use explicit tag
  """
  @spec get_log(Types.env(), atom()) :: [term()]
  def get_log(env, tag \\ @default_tag) do
    Env.get_state(env, state_key(tag), [])
  end

  #############################################################################
  ## IHandle Implementation
  #############################################################################

  @impl Skuld.Comp.IHandle
  def handle(op, env, k) do
    case op do
      {@tell_op, msg} ->
        sk = state_key(@default_tag)
        current = Env.get_state!(env, sk)
        updated = [msg | current]
        new_env = Env.put_state(env, sk, updated)
        k.(updated, new_env)

      @peek_op ->
        current = Env.get_state!(env, state_key(@default_tag))
        k.(current, env)

      {@set_log_op, new_log} ->
        new_env = Env.put_state(env, state_key(@default_tag), new_log)
        k.(:ok, new_env)
    end
  end

  #############################################################################
  ## Utilities
  #############################################################################

  @doc """
  Tell multiple messages.

  ## Examples

      Writer.tell_many(["a", "b", "c"])           # use default tag
      Writer.tell_many(:audit, ["a", "b", "c"])   # use explicit tag
  """
  @spec tell_many([term()]) :: Types.computation()
  def tell_many(messages) when is_list(messages) do
    tell_many(@default_tag, messages)
  end

  @spec tell_many(atom(), [term()]) :: Types.computation()
  def tell_many(tag, messages) when is_atom(tag) and is_list(messages) do
    Comp.traverse(messages, &tell(tag, &1))
  end

  @doc """
  Clear the log.

  ## Examples

      Writer.clear()        # use default tag
      Writer.clear(:audit)  # use explicit tag
  """
  @spec clear(atom()) :: Types.computation()
  def clear(tag \\ @default_tag) do
    set_log(tag, [])
  end

  #############################################################################
  ## State Key Helper
  #############################################################################

  @doc """
  Returns the env.state key used for a given tag.

  Useful for configuring EffectLogger's `state_keys` filter.

  ## Examples

      # Only capture Writer log in EffectLogger snapshots
      EffectLogger.with_logging(state_keys: [Writer.state_key(:audit)])

      # Multiple logs
      EffectLogger.with_logging(state_keys: [
        Writer.state_key(:audit),
        Writer.state_key(:metrics)
      ])
  """
  @spec state_key(atom()) :: {module(), atom()}
  def state_key(tag), do: {__MODULE__, tag}
end
