# Test effect module using def_op_struct.
#
# Defined in test/support/ so it is compiled before protocol consolidation,
# ensuring the Jason.Encoder implementations generated by def_op_struct are
# included in the consolidated protocol and can be tested without warnings.
defmodule Skuld.Test.OpStructEffect do
  @moduledoc false

  import Skuld.Comp.DefOpStruct

  alias Skuld.Comp

  @sig __MODULE__
  def sig, do: @sig

  # 0-field struct
  def_op_struct Ping

  # Single-field struct
  def_op_struct Greet, [:name]

  # Multi-field struct
  def_op_struct Add, [:a, :b]

  # Struct with atom_fields option
  def_op_struct Tagged, [:tag, :value], atom_fields: [:tag]

  # Struct with multiple atom_fields
  def_op_struct MultiAtom, [:op, :target, :data], atom_fields: [:op, :target]

  # API functions using the structs
  def ping, do: Comp.effect(@sig, %Ping{})
  def greet(name), do: Comp.effect(@sig, %Greet{name: name})
  def add(a, b), do: Comp.effect(@sig, %Add{a: a, b: b})
  def tagged(tag, value), do: Comp.effect(@sig, %Tagged{tag: tag, value: value})
end
