# Utilities for converting Elixir terms to/from JSON-friendly representations.
#
# Provides two layers:
#
# 1. **Struct encoding** (`encode/1` / `decode/1`) — converts structs to maps
#    with a `__struct__` key for faithful reconstruction. Used by Jason.Encoder
#    implementations generated by `def_op_struct`.
#
# 2. **Generic term encoding** (`encode_term/1` / `decode_term/1`) — recursively
#    converts arbitrary Elixir terms to JSON-safe representations using tagged
#    wrapper maps for types JSON doesn't natively support:
#    - Atoms: `%{"__atom__" => "ok"}`
#    - Tuples: `%{"__tuple__" => [encoded_elem1, encoded_elem2, ...]}`
#    - Structs: `%{"__struct__" => "Elixir.Module", field1: val1, ...}`
#    - Lists, maps, and JSON primitives pass through (with recursive encoding).
#
# Keys are expected to already exist as atoms in the system to avoid dynamic
# atom creation.
defmodule Skuld.Comp.SerializableStruct do
  @moduledoc false

  #############################################################################
  ## Struct encoding (used by def_op_struct)
  #############################################################################

  @doc """
  Convert a struct into a map representation suitable for JSON encoding.
  """
  @spec encode(struct) :: map
  def encode(%module{} = value) when is_atom(module) do
    value
    |> Map.from_struct()
    |> Map.put("__struct__", Atom.to_string(module))
  end

  @doc """
  Reconstructs a struct from a decoded JSON map produced by `encode/1`.
  If the map doesn't include struct metadata, it is returned unchanged.
  """
  @spec decode(map) :: struct | map
  def decode(map) when is_map(map) do
    case fetch_struct_module(map) do
      {:ok, module} ->
        if function_exported?(module, :from_json, 1) do
          module.from_json(map)
        else
          attrs =
            map
            |> Map.delete("__struct__")
            |> Map.delete(:__struct__)
            |> Enum.reduce(%{}, fn {k, v}, acc ->
              Map.put(acc, key_to_existing_atom(k), v)
            end)

          struct(module, attrs)
        end

      :error ->
        map
    end
  end

  def decode(value), do: value

  #############################################################################
  ## Generic term encoding (for EffectLogger data/value fields)
  #############################################################################

  @doc """
  Recursively encode an arbitrary Elixir term into a JSON-safe representation.

  Uses tagged wrapper maps for types JSON doesn't natively support:
  - `nil`, booleans, numbers, strings → pass through
  - atoms → `%{"__atom__" => "ok"}`
  - tuples → `%{"__tuple__" => [encoded_elements...]}`
  - structs → `%{"__struct__" => "Elixir.Module", field1: encoded_val1, ...}`
  - lists → recursively encoded lists
  - maps → recursively encoded maps (keys preserved as strings/numbers)
  """
  @spec encode_term(term()) :: term()
  def encode_term(nil), do: nil
  def encode_term(value) when is_boolean(value), do: value
  def encode_term(value) when is_number(value), do: value
  def encode_term(value) when is_binary(value), do: value

  def encode_term(value) when is_atom(value) do
    %{"__atom__" => Atom.to_string(value)}
  end

  def encode_term(value) when is_tuple(value) do
    elements =
      value
      |> Tuple.to_list()
      |> Enum.map(&encode_term/1)

    %{"__tuple__" => elements}
  end

  def encode_term(%module{} = value) when is_atom(module) do
    value
    |> Map.from_struct()
    |> Enum.reduce(%{"__struct__" => Atom.to_string(module)}, fn {k, v}, acc ->
      Map.put(acc, Atom.to_string(k), encode_term(v))
    end)
  end

  def encode_term(value) when is_list(value) do
    Enum.map(value, &encode_term/1)
  end

  def encode_term(value) when is_map(value) do
    Map.new(value, fn {k, v} -> {encode_term(k), encode_term(v)} end)
  end

  @doc """
  Recursively decode a JSON-decoded term back into the original Elixir term.

  Reverses the encoding from `encode_term/1`:
  - `%{"__atom__" => str}` → atom (via String.to_existing_atom)
  - `%{"__tuple__" => list}` → tuple (elements recursively decoded)
  - `%{"__struct__" => module, ...}` → struct (delegates to `decode/1`)
  - lists → recursively decoded lists
  - other values → pass through
  """
  @spec decode_term(term()) :: term()
  def decode_term(nil), do: nil
  def decode_term(value) when is_boolean(value), do: value
  def decode_term(value) when is_number(value), do: value
  def decode_term(value) when is_binary(value), do: value

  def decode_term(%{"__atom__" => str}) when is_binary(str) do
    String.to_existing_atom(str)
  end

  def decode_term(%{"__tuple__" => elements}) when is_list(elements) do
    elements
    |> Enum.map(&decode_term/1)
    |> List.to_tuple()
  end

  def decode_term(%{"__struct__" => _} = map) do
    # Recursively decode field values before delegating to struct decode,
    # so that from_json/1 callbacks receive decoded Elixir terms.
    decoded_fields = Map.new(map, fn {k, v} -> {k, decode_term(v)} end)
    decode(decoded_fields)
  end

  def decode_term(value) when is_map(value) do
    Map.new(value, fn {k, v} -> {k, decode_term(v)} end)
  end

  def decode_term(value) when is_list(value) do
    Enum.map(value, &decode_term/1)
  end

  defp fetch_struct_module(map) do
    case Map.get(map, "__struct__") || Map.get(map, :__struct__) do
      nil ->
        :error

      module when is_atom(module) ->
        ensure_loaded(module)

      struct_name when is_binary(struct_name) ->
        struct_name
        |> String.to_existing_atom()
        |> ensure_loaded()
    end
  rescue
    ArgumentError ->
      :error
  end

  defp ensure_loaded(module) do
    case Code.ensure_loaded(module) do
      {:module, _} ->
        if function_exported?(module, :__struct__, 0) do
          {:ok, module}
        else
          :error
        end

      _ ->
        :error
    end
  end

  defp key_to_existing_atom(key) when is_atom(key), do: key

  defp key_to_existing_atom(key) when is_binary(key) do
    String.to_existing_atom(key)
  end
end
