defmodule Skuld.Comp.DefOpStructTest do
  use ExUnit.Case, async: true

  alias Skuld.Comp
  alias Skuld.Comp.SerializableStruct

  # Uses Skuld.Test.OpStructEffect from test/support/test_op_struct_effect.ex
  # Defined there so it is compiled before protocol consolidation, ensuring the
  # Jason.Encoder implementations generated by def_op_struct are included.
  alias Skuld.Test.OpStructEffect

  describe "struct generation" do
    test "0-field struct is created with empty fields" do
      ping = %OpStructEffect.Ping{}
      assert ping == %OpStructEffect.Ping{}
      assert Map.keys(ping) -- [:__struct__] == []
    end

    test "single-field struct is created with field" do
      greet = %OpStructEffect.Greet{name: "Alice"}
      assert greet.name == "Alice"
    end

    test "multi-field struct is created with fields" do
      add = %OpStructEffect.Add{a: 1, b: 2}
      assert add.a == 1
      assert add.b == 2
    end

    test "struct fields default to nil" do
      greet = %OpStructEffect.Greet{}
      assert greet.name == nil

      add = %OpStructEffect.Add{}
      assert add.a == nil
      assert add.b == nil
    end

    test "struct with atom_fields is created" do
      tagged = %OpStructEffect.Tagged{tag: :my_tag, value: 42}
      assert tagged.tag == :my_tag
      assert tagged.value == 42
    end
  end

  describe "handler dispatch" do
    test "0-field struct dispatches to handler" do
      result =
        OpStructEffect.ping()
        |> Comp.with_handler(OpStructEffect, fn op, env, k ->
          assert %OpStructEffect.Ping{} = op
          k.(:pong, env)
        end)
        |> Comp.run!()

      assert result == :pong
    end

    test "single-field struct dispatches with field values" do
      result =
        OpStructEffect.greet("world")
        |> Comp.with_handler(OpStructEffect, fn op, env, k ->
          assert %OpStructEffect.Greet{name: "world"} = op
          k.("hello #{op.name}", env)
        end)
        |> Comp.run!()

      assert result == "hello world"
    end

    test "multi-field struct dispatches with all fields" do
      result =
        OpStructEffect.add(3, 4)
        |> Comp.with_handler(OpStructEffect, fn op, env, k ->
          assert %OpStructEffect.Add{a: 3, b: 4} = op
          k.(op.a + op.b, env)
        end)
        |> Comp.run!()

      assert result == 7
    end

    test "handler can pattern match on struct" do
      handler = fn
        %OpStructEffect.Ping{}, env, k -> k.(:pong, env)
        %OpStructEffect.Greet{name: name}, env, k -> k.("hi #{name}", env)
        %OpStructEffect.Add{a: a, b: b}, env, k -> k.(a + b, env)
      end

      assert :pong ==
               OpStructEffect.ping()
               |> Comp.with_handler(OpStructEffect, handler)
               |> Comp.run!()

      assert "hi Bob" ==
               OpStructEffect.greet("Bob")
               |> Comp.with_handler(OpStructEffect, handler)
               |> Comp.run!()

      assert 10 ==
               OpStructEffect.add(6, 4)
               |> Comp.with_handler(OpStructEffect, handler)
               |> Comp.run!()
    end
  end

  describe "Jason encoding" do
    test "0-field struct encodes to JSON" do
      json = Jason.encode!(%OpStructEffect.Ping{})
      decoded = Jason.decode!(json)
      assert decoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Ping"
    end

    test "single-field struct encodes to JSON" do
      json = Jason.encode!(%OpStructEffect.Greet{name: "Alice"})
      decoded = Jason.decode!(json)
      assert decoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Greet"
      assert decoded["name"] == "Alice"
    end

    test "multi-field struct encodes to JSON" do
      json = Jason.encode!(%OpStructEffect.Add{a: 1, b: 2})
      decoded = Jason.decode!(json)
      assert decoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Add"
      assert decoded["a"] == 1
      assert decoded["b"] == 2
    end

    test "nil fields are included in JSON" do
      json = Jason.encode!(%OpStructEffect.Greet{})
      decoded = Jason.decode!(json)
      assert Map.has_key?(decoded, "name")
      assert decoded["name"] == nil
    end

    test "struct with atom_fields encodes to JSON" do
      json = Jason.encode!(%OpStructEffect.Tagged{tag: :my_tag, value: 42})
      decoded = Jason.decode!(json)
      assert decoded["tag"] == "my_tag"
      assert decoded["value"] == 42
    end
  end

  describe "SerializableStruct.encode" do
    test "0-field struct encodes to map with __struct__ key" do
      encoded = SerializableStruct.encode(%OpStructEffect.Ping{})
      assert encoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Ping"
    end

    test "single-field struct encodes to map with fields" do
      encoded = SerializableStruct.encode(%OpStructEffect.Greet{name: "Alice"})
      assert encoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Greet"
      assert encoded[:name] == "Alice"
    end

    test "multi-field struct encodes to map with all fields" do
      encoded = SerializableStruct.encode(%OpStructEffect.Add{a: 1, b: 2})
      assert encoded["__struct__"] == "Elixir.Skuld.Test.OpStructEffect.Add"
      assert encoded[:a] == 1
      assert encoded[:b] == 2
    end

    test "nil fields are included in encoded map" do
      encoded = SerializableStruct.encode(%OpStructEffect.Greet{})
      assert Map.has_key?(encoded, :name)
      assert encoded[:name] == nil
    end
  end

  describe "SerializableStruct.encode/decode round-trip" do
    test "0-field struct round-trips" do
      original = %OpStructEffect.Ping{}
      encoded = SerializableStruct.encode(original)
      decoded = SerializableStruct.decode(encoded)
      assert decoded == original
    end

    test "single-field struct round-trips" do
      original = %OpStructEffect.Greet{name: "Alice"}
      encoded = SerializableStruct.encode(original)
      decoded = SerializableStruct.decode(encoded)
      assert decoded == original
    end

    test "multi-field struct round-trips" do
      original = %OpStructEffect.Add{a: 1, b: 2}
      encoded = SerializableStruct.encode(original)
      decoded = SerializableStruct.decode(encoded)
      assert decoded == original
    end
  end

  describe "JSON round-trip (encode -> JSON -> decode)" do
    test "0-field struct round-trips through JSON" do
      original = %OpStructEffect.Ping{}
      json = Jason.encode!(original)
      map = Jason.decode!(json)
      decoded = SerializableStruct.decode(map)
      assert decoded == original
    end

    test "single-field struct with string value round-trips through JSON" do
      original = %OpStructEffect.Greet{name: "Alice"}
      json = Jason.encode!(original)
      map = Jason.decode!(json)
      decoded = SerializableStruct.decode(map)
      assert decoded == original
    end

    test "multi-field struct with numeric values round-trips through JSON" do
      original = %OpStructEffect.Add{a: 1, b: 2}
      json = Jason.encode!(original)
      map = Jason.decode!(json)
      decoded = SerializableStruct.decode(map)
      assert decoded == original
    end
  end

  describe "atom_fields deserialization (from_json)" do
    test "from_json converts string atom_fields back to atoms" do
      # Simulate what happens after JSON decode — atom fields become strings
      map = %{"tag" => "my_tag", "value" => 42}
      result = OpStructEffect.Tagged.from_json(map)
      assert result == %OpStructEffect.Tagged{tag: :my_tag, value: 42}
    end

    test "from_json preserves atom values in atom_fields" do
      map = %{tag: :my_tag, value: 42}
      result = OpStructEffect.Tagged.from_json(map)
      assert result == %OpStructEffect.Tagged{tag: :my_tag, value: 42}
    end

    test "from_json handles nil atom_fields" do
      map = %{"tag" => nil, "value" => 42}
      result = OpStructEffect.Tagged.from_json(map)
      assert result == %OpStructEffect.Tagged{tag: nil, value: 42}
    end

    test "from_json does not convert non-atom fields" do
      map = %{"tag" => "my_tag", "value" => "a string value"}
      result = OpStructEffect.Tagged.from_json(map)
      assert result == %OpStructEffect.Tagged{tag: :my_tag, value: "a string value"}
    end

    test "from_json handles multiple atom_fields" do
      map = %{"op" => "insert", "target" => "users", "data" => %{name: "Alice"}}
      result = OpStructEffect.MultiAtom.from_json(map)

      assert result ==
               %OpStructEffect.MultiAtom{op: :insert, target: :users, data: %{name: "Alice"}}
    end

    test "struct with atom_fields round-trips through JSON" do
      original = %OpStructEffect.Tagged{tag: :my_tag, value: 42}
      json = Jason.encode!(original)
      map = Jason.decode!(json)

      # SerializableStruct.decode delegates to from_json when available
      decoded = SerializableStruct.decode(map)
      assert decoded == original
    end

    test "struct with multiple atom_fields round-trips through JSON" do
      original = %OpStructEffect.MultiAtom{op: :insert, target: :users, data: "payload"}
      json = Jason.encode!(original)
      map = Jason.decode!(json)
      decoded = SerializableStruct.decode(map)
      assert decoded == original
    end
  end

  describe "from_json is only generated when atom_fields present" do
    test "struct without atom_fields does not have from_json" do
      refute function_exported?(OpStructEffect.Ping, :from_json, 1)
      refute function_exported?(OpStructEffect.Greet, :from_json, 1)
      refute function_exported?(OpStructEffect.Add, :from_json, 1)
    end

    test "struct with atom_fields has from_json" do
      assert function_exported?(OpStructEffect.Tagged, :from_json, 1)
      assert function_exported?(OpStructEffect.MultiAtom, :from_json, 1)
    end
  end
end
