defmodule Skuld.Adapter.EffectfulContractTest do
  use ExUnit.Case, async: true

  alias Skuld.Comp
  alias Skuld.Effects.Port
  alias Skuld.Effects.Throw

  # DoubleDown contract
  defmodule TestContract do
    use DoubleDown.Contract

    defcallback get_item(id :: String.t()) :: {:ok, map()} | {:error, term()}
    defcallback list_items() :: [map()]
  end

  # Effectful contract generated from DoubleDown contract
  defmodule TestContract.Effectful do
    use Skuld.Adapter.EffectfulContract,
      double_down_contract: TestContract
  end

  # Implementation using the __using__ helper
  defmodule TestContract.Impl do
    use Skuld.Syntax
    use TestContract.Effectful

    def get_item(id) do
      comp do
        {:ok, %{id: id, name: "Item #{id}"}}
      end
    end

    def list_items do
      comp do
        [%{id: "1"}, %{id: "2"}]
      end
    end
  end

  # Facade to call through Port
  defmodule TestContract.Facade do
    use Skuld.Effects.Port.EffectfulFacade,
      contract: TestContract.Effectful
  end

  describe "__using__/1 on effectful contract" do
    test "generates @behaviour on the implementation module" do
      # __port_effectful__?/0 is generated by __using__
      assert TestContract.Impl.__port_effectful__?()
    end

    test "implementation is auto-detected as effectful in Port handler" do
      comp =
        TestContract.Facade.get_item("42")
        |> Port.with_handler(%{TestContract.Effectful => TestContract.Impl})
        |> Throw.with_handler()

      {result, _env} = Comp.run(comp)
      assert {:ok, %{id: "42", name: "Item 42"}} = result
    end

    test "explicit {:effectful, mod} also works" do
      comp =
        TestContract.Facade.get_item("99")
        |> Port.with_handler(%{TestContract.Effectful => {:effectful, TestContract.Impl}})
        |> Throw.with_handler()

      {result, _env} = Comp.run(comp)
      assert {:ok, %{id: "99", name: "Item 99"}} = result
    end

    test "list_items returns list" do
      comp =
        TestContract.Facade.list_items()
        |> Port.with_handler(%{TestContract.Effectful => TestContract.Impl})
        |> Throw.with_handler()

      {result, _env} = Comp.run(comp)
      assert [%{id: "1"}, %{id: "2"}] = result
    end
  end
end
